FROM ubuntu:22.04

#install necessary packages
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install -y wget bzip2 make unzip cppcheck libc6-dev\
    && rm -rf /var/lib/apt/lists/*

#create a non-root user name "ubuntu"
#but put in root group since GitHub actions needs permissions
#to create tmp files.
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo \
    -u 1001 ubuntu
USER ubuntu
WORKDIR /home/ubuntu
